spring.application.name=tour-trip-api

# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/etec_tour_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway settings
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration,classpath:db/seed

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method